spring:
  application:
    name: example-zuul

server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    api-a:
      path: /service/api-a/**
      serviceId: hello-service-1
    api-b:
      path: /service/api-b/**
      serviceId: feign-consumer
    data-statistic:
      path: /service/statistic/**
      serviceId: data-statistic
    experience-exchange:
      path: /service/experience/**
      serviceId: experience-exchange
